CREATE LOGIN _ADMIN
	WITH PASSWORD = 'strongPass'
CREATE USER _ADMIN FOR LOGIN _ADMIN;

CREATE LOGIN HEAD_LIBRARIAN
	WITH PASSWORD = 'strongPass'
CREATE USER HEAD_LIBRARIAN FOR LOGIN HEAD_LIBRARIAN;

CREATE LOGIN LIBRARIAN
	WITH PASSWORD = 'strongPass'
CREATE USER LIBRARIAN FOR LOGIN LIBRARIAN;