begin tran user_privileges

GRANT ALL PRIVILEGES ON GTLDB.* TO _ADMIN WITH GRANT OPTION;

grant SELECT, UPDATE, INSERT, ALTER ON NonLendable to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON SubjectArea to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON CoverType to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON LanguageType to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON AuthorName to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON Book to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON AcquireReason to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON AcquireList to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON Card to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON Loan to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON NoticeType to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON Notice to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON Orders to HEAD_LIBRARIAN
grant SELECT, UPDATE, INSERT, ALTER ON EmployeeType to HEAD_LIBRARIAN
grant SELECT, UPDATE ON Members to HEAD_LIBRARIAN
grant SELECT, UPDATE ON Addresses to HEAD_LIBRARIAN
grant SELECT ON Zip to HEAD_LIBRARIAN
grant SELECT ON State to HEAD_LIBRARIAN

deny DELETE, ALTER, INSERT ON Addresses to HEAD_LIBRARIAN
deny DELETE, ALTER, INSERT ON Members to HEAD_LIBRARIAN
deny DELETE, ALTER, INSERT, ALTER ON ZIP to HEAD_LIBRARIAN
deny DELETE, ALTER, INSERT, ALTER ON State to HEAD_LIBRARIAN

grant SELECT ON NonLendable to LIBRARIAN
grant SELECT ON SubjectArea to LIBRARIAN
grant SELECT ON CoverType to LIBRARIAN
grant SELECT ON LanguageType to LIBRARIAN
grant SELECT ON AuthorName to LIBRARIAN
grant SELECT ON AcquireReason to LIBRARIAN
grant SELECT ON EmployeeType to LIBRARIAN
grant SELECT ON Zip to LIBRARIAN
grant SELECT ON State to LIBRARIAN
grant SELECT ON NoticeType to LIBRARIAN
grant SELECT, UPDATE ON Addresses to LIBRARIAN
grant SELECT, UPDATE ON Members to LIBRARIAN
grant SELECT, UPDATE ON AcquireList to LIBRARIAN
grant SELECT, UPDATE ON Notice to LIBRARIAN
grant SELECT, UPDATE ON Loan to LIBRARIAN
grant SELECT, UPDATE ON Card to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Orders to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Book to LIBRARIAN

deny DELETE, ALTER, INSERT, UPDATE ON NonLendable to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON SubjectArea to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON CoverType to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON LanguageType to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON AuthorName to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON AcquireReason to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON EmployeeType to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON Zip to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON State to LIBRARIAN
deny DELETE, ALTER, INSERT, UPDATE ON NoticeType to LIBRARIAN
deny DELETE, ALTER, INSERT ON Addresses to LIBRARIAN
deny DELETE, ALTER, INSERT ON Members to LIBRARIAN
deny DELETE, ALTER, INSERT ON AcquireList to LIBRARIAN
deny DELETE, ALTER, INSERT ON Notice to LIBRARIAN
deny DELETE, ALTER, INSERT ON Loan to LIBRARIAN
deny DELETE, ALTER, INSERT ON Card to LIBRARIAN
deny DELETE, ALTER ON Book to LIBRARIAN
deny DELETE, ALTER ON Orders to LIBRARIAN

commit tran user_privileges